import Head from 'next/head'
import { useEffect} from 'react';
import React, { useState } from 'react';
import { ethers } from "ethers";
import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import NFTCard from 'src/pages/components/NFTCard'


export default function Home() {
  const [name, setName] = useState('0xaAdBA140Ae5e4c8a9eF0Cc86EA3124b446e3E46A');
  const [nfts, setNFTs] = useState([])
  const [isLoading, setIsLoading] = useState(true)
  // const [address, setAddress] = useState("");

  //function to fetch nfts by collection
  const fetchCollection = async () => {
    const provider = new ethers.JsonRpcProvider("https://palpable-winter-dust.discover.quiknode.pro/49c8a8a6ca1ca2fd9ec54f126e9d141cff451777/");
    console.log(provider);
    const collection = await provider.send("qn_fetchNFTsByCollection", {
      collection: name,
      page: 1,
      perPage: 10
    })
    console.log(collection);
    return collection
  }


  useEffect(() => {
    console.log(name);
    fetchCollection()
    .then(data => {
      setNFTs(data.tokens)
      setIsLoading(false)
      console.log(data)
    })
    .catch(err => setNFTs([]))
  }, [name]);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input type="text" value={name} onChange={(e) => setName(e.target.value)}/>
        <div className='grid grid-cols-3 gap-4'>
          {nfts.map(token => <NFTCard key={token.name} nft={token} />)}
        </div>
      </main>
    </>
  )
}
